config/routes.rb
DynamicFormsEngine::Engine.routes.draw do
	resources :dynamic_form_entries  do
    collection do
      get 'all_entries'
    end
  end
  
	match 'dynamic_form_entries/new/:dynamic_form_type_id', 
    to: 'dynamic_form_entries#new', 
    via: [:get, :post],
    as: "new_form_entry"

  match 'form_entries/:dynamic_form_type_id', 
    to: 'dynamic_form_entries#form_entries', 
    via: [:get],
    as: "form_entries"

  resources :dynamic_form_types

  namespace :api do
    get 'dynamic_forms_engine/dynamic_form_entries/get_many' => 'dynamic_form_entries#get_many'
  end
  
  root 'dynamic_form_types#index'
end

app/controllers/dynamic_forms_engine/api/dynamic_form_entries_controller.rb
require_dependency "dynamic_forms_engine/application_controller"

module DynamicFormsEngine
  class Api::DynamicFormEntriesController < ApplicationController

  	def get_many
  		if params[:form_type_id]
  			render json: format_json_response(DynamicFormType.find(params[:form_type_id].to_i).entries.includes(:dynamic_form_type))
  		else
  			render json: format_json_response(nil)
  		end
  	end


  	private

  	def format_json_response(data, meta=nil)
  		{data: data, meta: (meta || {code: 200})}.to_json
  	end

  end
end

app/controllers/dynamic_forms_engine/api/dynamic_form_types_controller.rb
require_dependency "dynamic_forms_engine/application_controller"

module DynamicFormsEngine
  class Api::DynamicFormTypesController < ApplicationController

  	def get_many
  		
  	end

  end
end

app/controllers/dynamic_forms_engine/application_controller.rb
class DynamicFormsEngine::ApplicationController < ApplicationController
	
	layout :set_iframe_layout

	def set_iframe_layout
	    Rails.logger.warn "\n\nPARAMS: #{params} IFRAME? #{params[:iframe]=="1"}\n\n\n"
	    # params[:iframe] == "1" ? "dynamic_forms_engine/iframe" : "application"
	    if params[:iframe] == "1"
	    	"dynamic_forms_engine/iframe"
	    elsif params[:format] == "print"
	    	"dynamic_forms_engine/dynamic_form_entries.print"
	    else
	    	"application"
	    end	
	end

	# def authenticate_user!
	    
	#     # stub
	    
	# end

end

app/controllers/dynamic_forms_engine/dynamic_form_fields_controller.rb
require_dependency "dynamic_forms_engine/application_controller"

module DynamicFormsEngine
	class DynamicFormFieldsController < ApplicationController 
		
	end


end

app/controllers/dynamic_forms_engine/dynamic_form_types_controller.rb
require_dependency "dynamic_forms_engine/application_controller"

module DynamicFormsEngine
  class DynamicFormTypesController < ApplicationController
    
    before_filter :authenticate_user!
    before_action :set_dynamic_form_type, only: [:show, :edit, :update, :destroy]
    # before_filter :non_editable_dynamic_forms, only: [:show, :edit, :update, :destroy]

    def index
      @dynamic_form_types = DynamicFormType.where(:user_id => current_user.id)
    end

    def show
      @form_fields = @dynamic_form_type.ordered_fields
    end

    def new
      @dynamic_form_type = DynamicFormType.new
    end

    def edit
    end

    def create
      create_dynamic_form_type(dynamic_form_type_params)
    end

    #Used for create AND save as
    def create_dynamic_form_type(params)
      @dynamic_form_type = DynamicFormType.new(params)
      @dynamic_form_type.user_id = current_user.id 
      respond_to do |format|
        if @dynamic_form_type.save
          format.html { redirect_to @dynamic_form_type, notice: 'Dynamic form type was successfully saved.' }
          format.json { render action: 'show', status: :created, location: @dynamic_form_type }
        else
          format.html { render action: 'new' }
          format.json { render json: @dynamic_form_type.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      if params[:save_as_button]
          # Strip out ids from old form
          # todo: DynamicFormType.sanitize_fields_before_dupe(fields) ??
          dynamic_form_type_params['fields_attributes'].each do |field|
              field[1].delete('id')
          end
          @dynamic_form_type = DynamicFormType.new(dynamic_form_type_params)
          @dynamic_form_type.user_id = current_user.id 
          if @dynamic_form_type.save
              redirect_to @dynamic_form_type, notice: 'Your new form has been saved.'
          else
              render action: 'edit'
          end
      elsif @dynamic_form_type.update(dynamic_form_type_params)
          redirect_to @dynamic_form_type, notice: 'Dynamic form type was successfully updated.'
      else
          render action: 'edit'
      end
    end
    
    def destroy
      @dynamic_form_type.destroy
      respond_to do |format|
        format.html { redirect_to dynamic_form_types_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_dynamic_form_type
        @dynamic_form_type = DynamicFormType.find(params[:id])
      end

      def non_editable_dynamic_forms
        if current_user.id != @dynamic_form_type.user_id 
          redirect_to(dynamic_form_entries_path, alert: 'Error: You can only view your own Dynamic forms' )
        end
      end
      # Never trust parameters from the scary internet, only allow the white list through.
      def dynamic_form_type_params
        params.require(:dynamic_form_type).permit(:name, :user_id, :description, :form_type,:is_public).tap do |whitelisted|
          whitelisted[:fields_attributes] = params[:dynamic_form_type][:fields_attributes] if !params[:dynamic_form_type][:fields_attributes].blank?
        end
      end

      
  end
end

app/helpers/dynamic_forms_engine/api/dynamic_form_types_helper.rb
module DynamicFormsEngine
  module Api::DynamicFormTypesHelper
  end
end

app/helpers/dynamic_forms_engine/application_helper.rb
module DynamicFormsEngine
  module ApplicationHelper

    def sign_form_field_tag(name, data)
      return hidden_field_tag(name,"", :hidden => true)+content_tag(:div,"",:id => "#{name}_sig")+
		      content_tag(:script,("jQuery(document).ready(function() {
		      		    var x = jQuery('##{name}_sig');
		      		    x.jSignature();
		      		    " + 
		      		    (!data.blank? && !(data == "image/jsignature;base30,") ? ("x.jSignature('setData', '#{data}', 'base30');
		      		    	" ) : "") + 
		      		    "jQuery('##{name}').val(x.jSignature('getData', 'base30'));
		      		    x.change(function(){
		      		      jQuery('##{name}').val(x.jSignature('getData', 'base30'));
		      		    });
		      		    
		      		  });").html_safe)
    end

  	
  	# Adds n-th number of contacts
	def link_to_add_fields(name, f, association)
		
		# new_object = f.object.send(association).klass.new
		# id = new_object.object_id
		
		# fields = f.fields_for(association, new_object, child_index: id) do |builder|
		# 	render(association.to_s.singularize + "_fields", f: builder)
		# end

		link_to(name, '#', class: "add_fields btn btn-info") 
			#data: {id: id, fields: fields.gsub("\n", "")})
	
	end
	
	# Adds n-th number of fields for dynamic form builder
	def link_to_add_many_fields(name, f, association)
		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize + "_fields", f: builder)
		end
		link_to(name, '#', class: "add_many_fields btn btn-info", data: {id: id, fields: fields.gsub("\n", "")})
	end

	# Creates display html for any object with address fields
	def display_address(obj)

		if !obj.blank? && obj.building_address
			ret = ""
			ret << strip_tags(obj.building_address)
			ret << "<br />"
			if !obj.building_address2.blank?
			 	ret << strip_tags(obj.building_address2)
			 	ret << "<br />"
			end
			ret << strip_tags("#{obj.building_city}, #{obj.building_state}  #{obj.building_zip}")

			return ret.html_safe
		else
			return "No Address"
		end
	end
	
	def us_states
	    [
	      ['-- Select --',''],
	      ['Alabama', 'AL'],
	      ['Alaska', 'AK'],
	      ['Arizona', 'AZ'],
	      ['Arkansas', 'AR'],
	      ['California', 'CA'],
	      ['Colorado', 'CO'],
	      ['Connecticut', 'CT'],
	      ['Delaware', 'DE'],
	      ['District of Columbia', 'DC'],
	      ['Florida', 'FL'],
	      ['Georgia', 'GA'],
	      ['Hawaii', 'HI'],
	      ['Idaho', 'ID'],
	      ['Illinois', 'IL'],
	      ['Indiana', 'IN'],
	      ['Iowa', 'IA'],
	      ['Kansas', 'KS'],
	      ['Kentucky', 'KY'],
	      ['Louisiana', 'LA'],
	      ['Maine', 'ME'],
	      ['Maryland', 'MD'],
	      ['Massachusetts', 'MA'],
	      ['Michigan', 'MI'],
	      ['Minnesota', 'MN'],
	      ['Mississippi', 'MS'],
	      ['Missouri', 'MO'],
	      ['Montana', 'MT'],
	      ['Nebraska', 'NE'],
	      ['Nevada', 'NV'],
	      ['New Hampshire', 'NH'],
	      ['New Jersey', 'NJ'],
	      ['New Mexico', 'NM'],
	      ['New York', 'NY'],
	      ['North Carolina', 'NC'],
	      ['North Dakota', 'ND'],
	      ['Ohio', 'OH'],
	      ['Oklahoma', 'OK'],
	      ['Oregon', 'OR'],
	      ['Pennsylvania', 'PA'],
	      ['Puerto Rico', 'PR'],
	      ['Rhode Island', 'RI'],
	      ['South Carolina', 'SC'],
	      ['South Dakota', 'SD'],
	      ['Tennessee', 'TN'],
	      ['Texas', 'TX'],
	      ['Utah', 'UT'],
	      ['Vermont', 'VT'],
	      ['Virginia', 'VA'],
	      ['Washington', 'WA'],
	      ['West Virginia', 'WV'],
	      ['Wisconsin', 'WI'],
	      ['Wyoming', 'WY']
	    ]
	end
  end
end

app/helpers/dynamic_forms_engine/dynamic_form_entries_helper.rb
module DynamicFormsEngine
  module DynamicFormEntriesHelper
  	

    # Loops over fields for this form and renders them
    def render_fields(dynamic_form_entry, builder)

      return_html = ""
      cols = 0
      form_group_exists = false
      dynamic_form_type = dynamic_form_entry.dynamic_form_type

      # raise keys: dynamic_form_entry.errors.keys, ids: dynamic_form_entry.ordered_fields.map(&:id)

      # For each field ...
      dynamic_form_type.ordered_fields.each_with_index do |field, i|

        next_field = dynamic_form_type.ordered_fields[i+1]

        # FIELDSET
        # if one field_group already exists, end one fieldset for the start of the next one
        if field.field_type == "field_group"
          if form_group_exists
            return_html += "</div>"         # Close row
            return_html += "<div class='clear spacer'></div>"   # Add spacer before fieldset close
            return_html += "</div></fieldset>"    # Close field set
            cols = 0
          end
          return_html += "<fieldset id='step_#{field.id}' data-field-group-name='#{field.name}' class='field-group'><legend class='legend-title'>#{field.name}</legend><div class='input-box'>"
          form_group_exists = true
        
        elsif field.field_type != "field_group"
          # ROWS
          if field.field_width != "false" && field.field_width.to_i > 0 
            return_html += '<div class="row dfe-fields-row">' if cols == 0  # New row
            # Update cols with field
            cols += field.field_width.to_i 
          end
          # close row and open new row
          if cols > 12
            return_html += "</div>"                             # Close row
            return_html += "<div class='clear spacer'></div>"   # Add spacer
            return_html += "<div class='row dfe-fields-row'>"   # Open new row
            cols = field.field_width.to_i
          end
        end

        errors = dynamic_form_entry.errors.full_messages_for(field.name.to_sym) if field.required?
        #errors are being added based on name, fields with same name will see errors 
        return_html += render_field_with_value(field,errors,builder,dynamic_form_entry)

      end

      return_html += "</div>"           # Last row

      # Add space between last row and fieldset end
      return_html += "<div class='clear spacer'></div>" 

      # FIELDSET - last closed
      return_html += "</div></fieldset>" if form_group_exists 
  
      # Add space between last field and submit button
      return_html += "<div class='clear spacer'></div>" 

      return_html.html_safe

    end

    def payment_status(dynamic_form_entry)
      if dynamic_form_entry.unpaid_app?
        link_to main_app.new_transaction_path(dynamic_form_entry), :class => 'btn btn-info', :title => 'Pay App fee if recent payment within 6 months', :rel => 'tooltip' do
          content_tag :i, '' , :class => 'fa fa-exclamation-triangle fa-lg'
        end
      elsif dynamic_form_entry.payment
        link_to '#', :class => 'btn btn-success' do
          content_tag :i, " Paid on #{dynamic_form_entry.payment.created_at.strftime('%-m/%-d/%y')}" , :class => 'fa fa-check-square-o fa-lg'
        end
      else
        content_tag :mark, 'Submit Application' 
      end
    end

    # Handles logic and rendering of individual field when creating dynamic form entries
    def render_field_with_value(field, errors, builder, dynamic_form_entry)
      field_value = nil
        if !dynamic_form_entry.properties[0].nil?
          dynamic_form_entry.properties.each do |key,value|
            if field.id == value[:id].to_i
              field_value = value[:value]
              break
            end
          end
        end
      render partial: "dynamic_forms_engine/dynamic_form_entries/fields/#{field.field_type}", 
             locals: {field: field, f: builder, errors: errors, field_value: field_value}
    end

    # builds date select
    # needs more refactoring when multiple date selects
    def date_select(f,field_id, field_value = nil)

      date_options = { "month_#{field_id}" => (1..12).map { |month| [Date::MONTHNAMES[month], month] }, 
                      "day_#{field_id}" => (1..31).to_a, 
                      "year_#{field_id}" => Time.now.year.downto(Time.now.year - 100).to_a }

      # if date exists, select it

      if !field_value.blank?
        date_object = Date.parse(field_value)

        date_values = [ date_object.mon, date_object.day, date_object.year]
      else
        date_values = ''
      end
      # builds the dropdowns
      date_dropdown = ""
      date_options.each_with_index do | (key, date), index |

        selected_value = params[key] || date_values[index]

        date_dropdown += select_tag(key, options_for_select(date, selected_value), { :class => 'form-control date-select', :style => 'width:auto; display:inline;'})
      end
      # selects date on failed form validation
      if params[date_options.keys[0]].present? && params[date_options.keys[1]].present? && params[date_options.keys[2]].present?
        field_date_object = Date.new(params[date_options.keys[2]].to_i , params[date_options.keys[0]].to_i, params[date_options.keys[1]].to_i)
        date_dropdown += f.hidden_field field_id, value: field_date_object, :class => "field-value form-control"
      else
        date_dropdown += f.hidden_field field_id, value: field_value, :class => "field-value form-control"
      end

      return date_dropdown.html_safe

    end



  end
end

app/helpers/dynamic_forms_engine/dynamic_form_types_helper.rb
module DynamicFormsEngine
  module DynamicFormTypesHelper
  end
end

app/views/dynamic_forms_engine/dynamic_form_entries/_building_apartments.js.erb
<script type="text/javascript">
$(document).ready(function(){

	var BUILDING_DROPDOWN = BUILDING_DROPDOWN || {};

	var tenant_app = <%= tenant_app %>
	// buildings API
	var buildings = <%= @building_apartments.html_safe %>;
	// apartment fieldset
	var $apartment_fieldset = $( tenant_app == true ? "fieldset[data-field-group-name='Apartment']" : "fieldset[data-field-group-name='Personal Info']" );
	// building and apartment row 
	var $apartment_row = $apartment_fieldset.children('.input-box').children(tenant_app == true ? "div:first" : "div:nth-child(6)");

	// building drowdown
	var $building_dropdown = $apartment_row.children("div:first").find("select");
	// apartment dropdown
	var $apartment_dropdown = $apartment_row.children("div:last").find("select");

	// Initialization functions
	BUILDING_DROPDOWN.initialPageSetup = function() {

		// Build out the buidling select menu
		$.each(buildings["buildings"], function(key,value){
			var building_address = (value["address1"] + ' ' + value["city"] + ', ' + value["state"] + ' ' + value["zip"]);
			$building_dropdown.append($("<option></option>").attr("value",value["id"]).text(building_address));
		});
		// Set the active option of the building select if one was specified by data-id
		if($building_dropdown.attr("data-id")){
			var building_id = $building_dropdown.data("id");
			$building_dropdown.val(building_id);	
		}

		// Build out the apartment select menu
		if(building_id == undefined){
			BUILDING_DROPDOWN.buildApartmentSizeSelectFromBuildingId($building_dropdown.val());
		}else{
			BUILDING_DROPDOWN.buildApartmentSizeSelectFromBuildingId(building_id);
		}

		// Set the active option of the apartment select if one was specified by data-id
		if($apartment_dropdown.attr("data-id")){
			var apartment_size = $apartment_dropdown.data("id");
			$apartment_dropdown.val(apartment_size);
		}
	};

	BUILDING_DROPDOWN.initializeEventListeners = function() {
		$building_dropdown
			.off( 'change' )
			.on(  'change', BUILDING_DROPDOWN.onBuildingSelectMenuChange );
	};

	// Event Handlers
	BUILDING_DROPDOWN.onBuildingSelectMenuChange = function( e ) {

		BUILDING_DROPDOWN.buildApartmentSizeSelectFromBuildingId(
			$(this).val()
		);
	};

	// @start: shared functions
	BUILDING_DROPDOWN.buildApartmentSizeSelectFromBuildingId = function( buildingId ) {
		buildingId = buildingId.toString();

		$apartment_dropdown.empty();
		$.each(buildings["buildings"],function(key, value){
			if(value.id == buildingId ){
				$.each(value.building_apartments,function(key,size){
					$apartment_dropdown.append(
						$("<option></option>")
							.attr("value",size["name"])
							.text(size["name"])
					);
				});
			}
		});
	};
	// @end: shared functions
	BUILDING_DROPDOWN.initialPageSetup();
	BUILDING_DROPDOWN.initializeEventListeners();	
});
</script>

app/views/dynamic_forms_engine/dynamic_form_entries/_default_form.html.erb
<%= form_for(dynamic_form_entry, :html => {:class => "form-horizontal", :multipart => true}) do |f| %>
    <%= hidden_field_tag("iframe", "1") if params[:iframe] == "1" %>

    <% if dynamic_form_entry.errors.any? %>
      <div class="row">
        <div class="well" id ="errors">
          <h2>This form contains <%= pluralize(dynamic_form_entry.errors.count, "error") %></h2>
          <ul>
            <% dynamic_form_entry.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>

  <%= f.hidden_field  :dynamic_form_type_id, :value => @dynamic_form_type.id %>

  <%= f.fields_for :properties, OpenStruct.new(Hash[dynamic_form_entry.properties.map{|k,v| [k.to_s, v]}]) do |builder| %>
    <%= render_fields(dynamic_form_entry, builder) %>
  <% end %>


<%# if dynamic_form_entry.new_record? %>
  <%#= f.fields_for :properties, OpenStruct.new(dynamic_form_entry.properties) do |builder| %>
  <%#= render_fields(dynamic_form_entry, builder) %>
  <%# end %>
<%# else %>
  <%#= f.fields_for :properties, OpenStruct.new(Hash[dynamic_form_entry.properties.map{|k,v| [k.to_s, v]}]) do |builder| %>
  <%#= render_fields(dynamic_form_entry, builder) %>
  <%# end %>
<%# end %>

  <div class="actions col-md-offset-2 col-sm-8">
    <%= submit_tag "Save Form", :name => "submit_entry", :class => "btn btn-success btn-block btn-lg" %>
    <span class="required required-tag">* </span>Indicates a required field!
  </div>

<% end %>

app/views/dynamic_forms_engine/dynamic_form_entries/_field_group.html.erb
<script type="text/javascript">
  <%= render partial: 'field_group.js' %>
</script>

app/views/dynamic_forms_engine/dynamic_form_entries/_form_action.js.erb
DefaultFieldBehavoir = function(){
  $('.datepicker').datepicker();
  $('.jsig').on('click',function(){
      $(window).resize();
  });
  $('.option-other').on('change', function(){
    if($(this).val() == "Other"){
      $(this).closest('.options_select_container')
        .find('.option-field').show()
        .find('.other-select').removeAttr('disabled');
    }
    else if($(this).val() != "Other"){
    	$(this).closest('.options_select_container')
         .find('.option-field').hide()
         .find(".other-select").attr('disabled','disabled');
      }
    });
    if($('small.error-msg').length > 0){
      $('small').parent().parent().addClass('has-error');
    }
}
DefaultFieldBehavoir();

app/views/dynamic_forms_engine/dynamic_form_entries/_print_pdf_css.html.erb
<style type="text/css">
  #print-page{
      width: 80%;
      padding-left: 10%;
  }
  table, th,td, .print-table{
    border: 1px solid black;
  }
  th:nth-child(n+5), td:nth-child(n+5){
    display: none;
  }
  .print-title, .print-title-size{
    
    text-align: center;
  }
  .print-table label{
    font-weight: bolder;
  }
</style>

app/views/dynamic_forms_engine/dynamic_form_entries/form_entries.html.erb
<div class="row">
  <div class="col-md-6">

    <ol class="breadcrumb header transparent-background">
        <li><%= link_to "Forms", dynamic_form_types_path %></li>
        <li><%= @dynamic_form_type.name %></li>
        <li class="active"><%= @dynamic_form_entries.size %> Entries</li>
        
    </ol>

  </div>
  <div class="col-md-6">
    <div class="btn-group pull-right hide-print">
      <%= link_to "Embed", form_entries_path(@dynamic_form_type, format: 'iframe'), class: 'btn btn-default' %>

      <%= link_to "CSV", form_entries_path(@dynamic_form_type, format: 'csv'), class: 'btn btn-default' %>
      <%= link_to "Excel", form_entries_path(@dynamic_form_type, format: 'xml'), class: 'btn btn-default' %>
      <%= link_to "Share Form", '#', data: {toggle: 'modal', target: "#share-#{@dynamic_form_type.id}"}, class: 'btn btn-default' %>
      <%= render partial: 'dynamic_forms_engine/dynamic_form_types/share_modal', locals: {dynamic_form_type: @dynamic_form_type} %>

      <%= link_to 'Edit Form', edit_dynamic_form_type_path(@dynamic_form_type), class: 'btn btn-primary ' %>
      <%= link_to 'View Form', new_form_entry_path(@dynamic_form_type), class: 'btn btn-info ' %>
    </div>
  </div>
</div>

<fieldset>
  <%= form_for(:search, :url => dynamic_form_entries_path, :html => { :method => :get }) do  %>
    <div class="row">
      <div class="col-xs-6 col-sm-3">
        <%= select("search","name",@entries_name, {:prompt => 'Select Form Type'},:class => 'form-control') %>
      </div>
      <div class="col-xs-3 col-sm-3">
        <%=raw text_field 'search', 'properties', :class => "col-xs-6 form-control", :placeholder => "Enter properties like" %>
      </div>
      <div class="col-md-3">
        <div class="input-daterange input-group date">
          <%= text_field 'search', 'start', :class => "form-control", :placeholder => "Start Date" %>
          <span class="input-group-addon">to</span>
           <%= text_field 'search', 'end', :class => "form-control", :placeholder => "End Date" %>
        </div>
      </div>

       <% if params[:search]
        print_url = request.original_url.sub!('form_entries?','form_entries.print?')
      else 
        print_url = form_entries_path(@dynamic_form_type, format: :print)
      end %>
      
      <div class="col-xs-6 col-sm-3">
        <div class="btn-group pull-right">
          <%= link_to "Reset", dynamic_form_entries_path, :class => 'btn btn-danger' %>
          <button type="submit" class="btn btn-info"><i class="fa fa-search"></i> Search</button>
          <%= link_to print_url,:class => 'print-index btn btn-success' do %>
            <i class="fa fa-print"></i> Print
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</fieldset>

<%= content_tag :div, nil, class: 'clear spacer' %>

<table class="table table-striped table-hover">
  <thead>
    <tr class="well">
      <th>Status</th>

      <% @dynamic_form_type.fields.each do |field| %>

        <% if field.included_in_report  && !DynamicFormsEngine::DynamicFormField.default_width.include?(field.field_type) %>
          <th align="center">
            <%= field.name %>
            <h6>(<%= field.field_type.titleize  %>)</h6>
          </th>
        <% end %>
      <% end %>
      <th>Submitted</th>
      <th width="1%"></th>
      <th width="1%"></th>
      <th width="1%"></th>
      <th width="1%"></th>
    </tr>
  </thead>


  <tbody>
    <% if @dynamic_form_entries %>
      <% @dynamic_form_entries.each do |dynamic_form_entry| %>
        <tr>

          <td>
            <% if dynamic_form_entry.in_progress %>
              <%= link_to edit_dynamic_form_entry_path(dynamic_form_entry), :class => 'btn btn-danger' do %>
                <i class="fa fa-pencil-square-o"></i> IN DRAFT
              <% end %>
            <% else %>
              <%= link_to dynamic_form_entry, :class => 'btn btn-success' do %>
                <i class="fa fa-check"></i> SUBMITTED
              <% end %>
            <% end %>
          </td>

          <% @dynamic_form_type.fields.each do |field| %>
          
            <% if field.included_in_report && !DynamicFormsEngine::DynamicFormField.default_width.include?(field.field_type) %>
              <% if field.field_type == "agreement" || field.field_type == "check_box" %>
                <td>
                  <%= "Approve" if dynamic_form_entry.properties.find { |key, value| value[:id].to_i == field.id } %>
                </td>
              <% elsif field.field_type == "signature" %>
                <td>
                  <%= "Signed" if !dynamic_form_entry.signature.nil? %>
                </td>
              <% else %>
                <td>
                  <% if !dynamic_form_entry.properties.blank? %>
                    <%#= dynamic_form_entry.properties.find { |key, value|  value[:id].to_i == field.id }[1][:value] %>
                    <%= dynamic_form_entry.get_property_value(field.id) %>
                    <%#= field.id %>
                  <% end %>
                </td>
              <% end %>
            <% end %>
          <% end %>

          <td><%= dynamic_form_entry.created_at.strftime(" %l:%M %p %b. %d, %Y") %></td>

          <td><%= link_to 'CSV', dynamic_form_entry_path(dynamic_form_entry, format: :csv), :class => 'btn btn-default' %></td>
          <td><%= link_to 'XML', dynamic_form_entry_path(dynamic_form_entry, format: :xml), :class => 'btn btn-default'%></td>
          <td><%= link_to 'View', dynamic_form_entry, :class => 'btn btn-info' %></td>
          <td>
            <%= link_to 'Delete', dynamic_form_entry, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
          </td>
          
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td>You have no entries!</td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function(){
    $('.date input').datepicker({
    });
  });
</script>