config/routes.rb
DynamicFormsEngine::Engine.routes.draw do
	resources :dynamic_form_entries  do
    collection do
      get 'all_entries'
    end
  end
  
	match 'dynamic_form_entries/new/:dynamic_form_type_id', 
    to: 'dynamic_form_entries#new', 
    via: [:get, :post],
    as: "new_form_entry"

  match 'form_entries/:dynamic_form_type_id', 
    to: 'dynamic_form_entries#form_entries', 
    via: [:get],
    as: "form_entries"

  resources :dynamic_form_types

  namespace :api do
    get 'dynamic_forms_engine/dynamic_form_entries/get_many' => 'dynamic_form_entries#get_many'
  end
  
  root 'dynamic_form_types#index'
end

app/controllers/dynamic_forms_engine/api/dynamic_form_entries_controller.rb
require_dependency "dynamic_forms_engine/application_controller"

module DynamicFormsEngine
  class Api::DynamicFormEntriesController < ApplicationController

  	def get_many
  		if params[:form_type_id]
  			render json: format_json_response(DynamicFormType.find(params[:form_type_id].to_i).entries.includes(:dynamic_form_type))
  		else
  			render json: format_json_response(nil)
  		end
  	end


  	private

  	def format_json_response(data, meta=nil)
  		{data: data, meta: (meta || {code: 200})}.to_json
  	end

  end
end

app/controllers/dynamic_forms_engine/api/dynamic_form_types_controller.rb
require_dependency "dynamic_forms_engine/application_controller"

module DynamicFormsEngine
  class Api::DynamicFormTypesController < ApplicationController

  	def get_many
  		
  	end

  end
end

app/controllers/dynamic_forms_engine/application_controller.rb
class DynamicFormsEngine::ApplicationController < ApplicationController
	
	layout :set_iframe_layout

	def set_iframe_layout
	    Rails.logger.warn "\n\nPARAMS: #{params} IFRAME? #{params[:iframe]=="1"}\n\n\n"
	    # params[:iframe] == "1" ? "dynamic_forms_engine/iframe" : "application"
	    if params[:iframe] == "1"
	    	"dynamic_forms_engine/iframe"
	    elsif params[:format] == "print"
	    	"dynamic_forms_engine/dynamic_form_entries.print"
	    else
	    	"application"
	    end	
	end

	# def authenticate_user!
	    
	#     # stub
	    
	# end

end

app/controllers/dynamic_forms_engine/dynamic_form_fields_controller.rb
require_dependency "dynamic_forms_engine/application_controller"

module DynamicFormsEngine
	class DynamicFormFieldsController < ApplicationController 
		
	end


end

app/controllers/dynamic_forms_engine/dynamic_form_types_controller.rb
require_dependency "dynamic_forms_engine/application_controller"

module DynamicFormsEngine
  class DynamicFormTypesController < ApplicationController
    
    before_filter :authenticate_user!
    before_action :set_dynamic_form_type, only: [:show, :edit, :update, :destroy]
    # before_filter :non_editable_dynamic_forms, only: [:show, :edit, :update, :destroy]

    def index
      @dynamic_form_types = DynamicFormType.where(:user_id => current_user.id)
    end

    def show
      @form_fields = @dynamic_form_type.ordered_fields
    end

    def new
      @dynamic_form_type = DynamicFormType.new
    end

    def edit
    end

    def create
      create_dynamic_form_type(dynamic_form_type_params)
    end

    #Used for create AND save as
    def create_dynamic_form_type(params)
      @dynamic_form_type = DynamicFormType.new(params)
      @dynamic_form_type.user_id = current_user.id 
      respond_to do |format|
        if @dynamic_form_type.save
          format.html { redirect_to @dynamic_form_type, notice: 'Dynamic form type was successfully saved.' }
          format.json { render action: 'show', status: :created, location: @dynamic_form_type }
        else
          format.html { render action: 'new' }
          format.json { render json: @dynamic_form_type.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      if params[:save_as_button]
          # Strip out ids from old form
          # todo: DynamicFormType.sanitize_fields_before_dupe(fields) ??
          dynamic_form_type_params['fields_attributes'].each do |field|
              field[1].delete('id')
          end
          @dynamic_form_type = DynamicFormType.new(dynamic_form_type_params)
          @dynamic_form_type.user_id = current_user.id 
          if @dynamic_form_type.save
              redirect_to @dynamic_form_type, notice: 'Your new form has been saved.'
          else
              render action: 'edit'
          end
      elsif @dynamic_form_type.update(dynamic_form_type_params)
          redirect_to @dynamic_form_type, notice: 'Dynamic form type was successfully updated.'
      else
          render action: 'edit'
      end
    end
    
    def destroy
      @dynamic_form_type.destroy
      respond_to do |format|
        format.html { redirect_to dynamic_form_types_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_dynamic_form_type
        @dynamic_form_type = DynamicFormType.find(params[:id])
      end

      def non_editable_dynamic_forms
        if current_user.id != @dynamic_form_type.user_id 
          redirect_to(dynamic_form_entries_path, alert: 'Error: You can only view your own Dynamic forms' )
        end
      end
      # Never trust parameters from the scary internet, only allow the white list through.
      def dynamic_form_type_params
        params.require(:dynamic_form_type).permit(:name, :user_id, :description, :form_type,:is_public).tap do |whitelisted|
          whitelisted[:fields_attributes] = params[:dynamic_form_type][:fields_attributes] if !params[:dynamic_form_type][:fields_attributes].blank?
        end
      end

      
  end
end

app/helpers/dynamic_forms_engine/api/dynamic_form_types_helper.rb
module DynamicFormsEngine
  module Api::DynamicFormTypesHelper
  end
end

app/helpers/dynamic_forms_engine/application_helper.rb
module DynamicFormsEngine
  module ApplicationHelper

    def sign_form_field_tag(name, data)
      return hidden_field_tag(name,"", :hidden => true)+content_tag(:div,"",:id => "#{name}_sig")+
		      content_tag(:script,("jQuery(document).ready(function() {
		      		    var x = jQuery('##{name}_sig');
		      		    x.jSignature();
		      		    " + 
		      		    (!data.blank? && !(data == "image/jsignature;base30,") ? ("x.jSignature('setData', '#{data}', 'base30');
		      		    	" ) : "") + 
		      		    "jQuery('##{name}').val(x.jSignature('getData', 'base30'));
		      		    x.change(function(){
		      		      jQuery('##{name}').val(x.jSignature('getData', 'base30'));
		      		    });
		      		    
		      		  });").html_safe)
    end

  	
  	# Adds n-th number of contacts
	def link_to_add_fields(name, f, association)
		
		# new_object = f.object.send(association).klass.new
		# id = new_object.object_id
		
		# fields = f.fields_for(association, new_object, child_index: id) do |builder|
		# 	render(association.to_s.singularize + "_fields", f: builder)
		# end

		link_to(name, '#', class: "add_fields btn btn-info") 
			#data: {id: id, fields: fields.gsub("\n", "")})
	
	end
	
	# Adds n-th number of fields for dynamic form builder
	def link_to_add_many_fields(name, f, association)
		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize + "_fields", f: builder)
		end
		link_to(name, '#', class: "add_many_fields btn btn-info", data: {id: id, fields: fields.gsub("\n", "")})
	end

	# Creates display html for any object with address fields
	def display_address(obj)

		if !obj.blank? && obj.building_address
			ret = ""
			ret << strip_tags(obj.building_address)
			ret << "<br />"
			if !obj.building_address2.blank?
			 	ret << strip_tags(obj.building_address2)
			 	ret << "<br />"
			end
			ret << strip_tags("#{obj.building_city}, #{obj.building_state}  #{obj.building_zip}")

			return ret.html_safe
		else
			return "No Address"
		end
	end
	
	def us_states
	    [
	      ['-- Select --',''],
	      ['Alabama', 'AL'],
	      ['Alaska', 'AK'],
	      ['Arizona', 'AZ'],
	      ['Arkansas', 'AR'],
	      ['California', 'CA'],
	      ['Colorado', 'CO'],
	      ['Connecticut', 'CT'],
	      ['Delaware', 'DE'],
	      ['District of Columbia', 'DC'],
	      ['Florida', 'FL'],
	      ['Georgia', 'GA'],
	      ['Hawaii', 'HI'],
	      ['Idaho', 'ID'],
	      ['Illinois', 'IL'],
	      ['Indiana', 'IN'],
	      ['Iowa', 'IA'],
	      ['Kansas', 'KS'],
	      ['Kentucky', 'KY'],
	      ['Louisiana', 'LA'],
	      ['Maine', 'ME'],
	      ['Maryland', 'MD'],
	      ['Massachusetts', 'MA'],
	      ['Michigan', 'MI'],
	      ['Minnesota', 'MN'],
	      ['Mississippi', 'MS'],
	      ['Missouri', 'MO'],
	      ['Montana', 'MT'],
	      ['Nebraska', 'NE'],
	      ['Nevada', 'NV'],
	      ['New Hampshire', 'NH'],
	      ['New Jersey', 'NJ'],
	      ['New Mexico', 'NM'],
	      ['New York', 'NY'],
	      ['North Carolina', 'NC'],
	      ['North Dakota', 'ND'],
	      ['Ohio', 'OH'],
	      ['Oklahoma', 'OK'],
	      ['Oregon', 'OR'],
	      ['Pennsylvania', 'PA'],
	      ['Puerto Rico', 'PR'],
	      ['Rhode Island', 'RI'],
	      ['South Carolina', 'SC'],
	      ['South Dakota', 'SD'],
	      ['Tennessee', 'TN'],
	      ['Texas', 'TX'],
	      ['Utah', 'UT'],
	      ['Vermont', 'VT'],
	      ['Virginia', 'VA'],
	      ['Washington', 'WA'],
	      ['West Virginia', 'WV'],
	      ['Wisconsin', 'WI'],
	      ['Wyoming', 'WY']
	    ]
	end
  end
end

app/helpers/dynamic_forms_engine/dynamic_form_entries_helper.rb
module DynamicFormsEngine
  module DynamicFormEntriesHelper
  	

    # Loops over fields for this form and renders them
    def render_fields(dynamic_form_entry, builder)

      return_html = ""
      cols = 0
      form_group_exists = false
      dynamic_form_type = dynamic_form_entry.dynamic_form_type

      # raise keys: dynamic_form_entry.errors.keys, ids: dynamic_form_entry.ordered_fields.map(&:id)

      # For each field ...
      dynamic_form_type.ordered_fields.each_with_index do |field, i|

        next_field = dynamic_form_type.ordered_fields[i+1]

        # FIELDSET
        # if one field_group already exists, end one fieldset for the start of the next one
        if field.field_type == "field_group"
          if form_group_exists
            return_html += "</div>"         # Close row
            return_html += "<div class='clear spacer'></div>"   # Add spacer before fieldset close
            return_html += "</div></fieldset>"    # Close field set
            cols = 0
          end
          return_html += "<fieldset id='step_#{field.id}' data-field-group-name='#{field.name}' class='field-group'><legend class='legend-title'>#{field.name}</legend><div class='input-box'>"
          form_group_exists = true
        
        elsif field.field_type != "field_group"
          # ROWS
          if field.field_width != "false" && field.field_width.to_i > 0 
            return_html += '<div class="row dfe-fields-row">' if cols == 0  # New row
            # Update cols with field
            cols += field.field_width.to_i 
          end
          # close row and open new row
          if cols > 12
            return_html += "</div>"                             # Close row
            return_html += "<div class='clear spacer'></div>"   # Add spacer
            return_html += "<div class='row dfe-fields-row'>"   # Open new row
            cols = field.field_width.to_i
          end
        end

        errors = dynamic_form_entry.errors.full_messages_for(field.name.to_sym) if field.required?
        #errors are being added based on name, fields with same name will see errors 
        return_html += render_field_with_value(field,errors,builder,dynamic_form_entry)

      end

      return_html += "</div>"           # Last row

      # Add space between last row and fieldset end
      return_html += "<div class='clear spacer'></div>" 

      # FIELDSET - last closed
      return_html += "</div></fieldset>" if form_group_exists 
  
      # Add space between last field and submit button
      return_html += "<div class='clear spacer'></div>" 

      return_html.html_safe

    end

    def payment_status(dynamic_form_entry)
      if dynamic_form_entry.unpaid_app?
        link_to main_app.new_transaction_path(dynamic_form_entry), :class => 'btn btn-info', :title => 'Pay App fee if recent payment within 6 months', :rel => 'tooltip' do
          content_tag :i, '' , :class => 'fa fa-exclamation-triangle fa-lg'
        end
      elsif dynamic_form_entry.payment
        link_to '#', :class => 'btn btn-success' do
          content_tag :i, " Paid on #{dynamic_form_entry.payment.created_at.strftime('%-m/%-d/%y')}" , :class => 'fa fa-check-square-o fa-lg'
        end
      else
        content_tag :mark, 'Submit Application' 
      end
    end

    # Handles logic and rendering of individual field when creating dynamic form entries
    def render_field_with_value(field, errors, builder, dynamic_form_entry)
      field_value = nil
        if !dynamic_form_entry.properties[0].nil?
          dynamic_form_entry.properties.each do |key,value|
            if field.id == value[:id].to_i
              field_value = value[:value]
              break
            end
          end
        end
      render partial: "dynamic_forms_engine/dynamic_form_entries/fields/#{field.field_type}", 
             locals: {field: field, f: builder, errors: errors, field_value: field_value}
    end

    # builds date select
    # needs more refactoring when multiple date selects
    def date_select(f,field_id, field_value = nil)

      date_options = { "month_#{field_id}" => (1..12).map { |month| [Date::MONTHNAMES[month], month] }, 
                      "day_#{field_id}" => (1..31).to_a, 
                      "year_#{field_id}" => Time.now.year.downto(Time.now.year - 100).to_a }

      # if date exists, select it

      if !field_value.blank?
        date_object = Date.parse(field_value)

        date_values = [ date_object.mon, date_object.day, date_object.year]
      else
        date_values = ''
      end
      # builds the dropdowns
      date_dropdown = ""
      date_options.each_with_index do | (key, date), index |

        selected_value = params[key] || date_values[index]

        date_dropdown += select_tag(key, options_for_select(date, selected_value), { :class => 'form-control date-select', :style => 'width:auto; display:inline;'})
      end
      # selects date on failed form validation
      if params[date_options.keys[0]].present? && params[date_options.keys[1]].present? && params[date_options.keys[2]].present?
        field_date_object = Date.new(params[date_options.keys[2]].to_i , params[date_options.keys[0]].to_i, params[date_options.keys[1]].to_i)
        date_dropdown += f.hidden_field field_id, value: field_date_object, :class => "field-value form-control"
      else
        date_dropdown += f.hidden_field field_id, value: field_value, :class => "field-value form-control"
      end

      return date_dropdown.html_safe

    end



  end
end

app/helpers/dynamic_forms_engine/dynamic_form_types_helper.rb
module DynamicFormsEngine
  module DynamicFormTypesHelper
  end
end

app/views/dynamic_forms_engine/dynamic_form_types/_default_form.html.erb
<%= form_for(@dynamic_form_type, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @dynamic_form_type.errors.any? %>
    <div class="well" id ="errors">
      <h2>This form type contains <%= pluralize(@dynamic_form_type.errors.count, "error") %></h2>
      <ul>
      <% @dynamic_form_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control", :required => true,:placeholder => 'Name of form' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :description, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, :class => "form-control", :required => true, :placeholder => 'Description of form' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :form_type, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :form_type,['Default-form','Multi-step'],{:disabled => 'Choose Form', :include_blank => 'Choose form'}, {:class => 'form-control input-medium form-type'} %>
    </div>
  </div>

  <div class="field form-group">
    <div class="col-sm-2 control-label">
      <%= link_to_add_many_fields "Add Field", f, :fields %>
    </div>

    <div class="col-sm-10" id="field_fields" >
      <%=raw "<em id='no_field_fields' style='width: 100%; color: red; text-align: center; padding-top: 13px;display: block;'>You need at least one field to submit this form!</em>" if @dynamic_form_type.fields.blank? %>
      <%= f.fields_for :fields do |builder| %>
        <%= render 'field_fields', f: builder %>
      <% end %>
    </div>
  </div>

  <div class="actions col-md-offset-2 col-sm-10">
    <%= f.submit "Save Form", :class => "btn btn-success btn-block btn-lg" %>
  </div>
<% end %>

<style type="text/css">

fieldset .checkbox{
  display: none;
}
fieldset .options_select {
  display: none;
}

fieldset[selection="text_field"] .options_select,{
  display:none;
}
/*fieldset[selection="contacts"] .checkbox,fieldset[selection="file_upload"] .checkbox{
  display: block; 
}
fieldset[selection="text_field"] .checkbox,fieldset[selection="text_area"] .checkbox {
  display: block; 
}
fieldset[selection="options_select"] .options_select,fieldset[selection="options_select"] .checkbox {
  display: block; 
}*/
fieldset[selection="email_validation"] .checkbox,fieldset[selection="phone_validation"] .checkbox {
  display: block; 
}
fieldset[selection="currency"] .checkbox,fieldset[selection="calendar"] .checkbox {
  display: block; 
}
fieldset[selection="text_area"] .checkbox,fieldset[selection="text_field"] .checkbox {
  display: block; 
}
fieldset[selection="large_header"] .options_select,fieldset[selection="large_header"] .checkbox{
  display: none;
}
fieldset[selection="options_select"] .options_select,fieldset[selection="options_select"]  {
  display: block; 
}
fieldset[selection="options_select_with_other"] .options_select,fieldset[selection="options_select_with_other"]  {
  display: block; 
}
fieldset[selection="medium_header"] .options_select,fieldset[selection="medium_header"] .checkbox{
  display: none;
}
fieldset[selection="small_header"] .options_select,fieldset[selection="small_header"] .checkbox{
  display: none;
}
fieldset[selection="contacts"] .options_select,fieldset[selection="contacts"] .checkbox{
  display: none;
}

</style>
<script type="text/javascript">
// $(document).ready(function(){
window.updatePopover = function($container, content){
  //console.log('updatePopover : ',container);
  $container.find('.field-popover').data('bs.popover').options.content = content; //this is defining the content params
};

window.init = function() {

    $("body").on("change", '.field_type', function() {


        var $this = $(this),                                // Field type drop down
            $container = $this.closest("fieldset");           // Fieldset container
            check_option = $this.val();                     // String with selected $this

        $container.find('.field-popover').popover({
                      trigger: 'hover',
                      title: 'Name of Field', 
                      placement: "top"});
        $container.attr('selection',check_option);
        switch (check_option)
        {
          case "options_select":
            // $container.children('.options_select').show();
            updatePopover($container,'Here you can create a drop down list with different options. Enter each option seperated by comma such as Option1, Option2, Option3');
            // $container.find('.checkbox').show();
            $('.options_field').popover({
                      placement: 'top',
                      trigger: 'hover',
                      title: 'Option field',
                      content: 'Enter each option seperated by comma'
                  });
            break;

          case "options_select_with_other":
            updatePopover($container,'Same as options select but with other option and enter option');
            $('.options_field').popover({
                      placement: 'top',
                      trigger: 'hover',
                      title: 'Option field with other',
                      content: 'Enter each option seperated by comma'
                  });
            break;

          case "phone_validation":
          updatePopover($container,'Validate a phone number');
          break;

          case "signature":
          updatePopover($container,'Add a signature field');
          break;

          case "field_group":
          updatePopover($container,'Add a fieldset group');
          break;

          case "large_header":
          updatePopover($container,'Give a LARGE header name');
          break;

          case "medium_header":
          updatePopover($container,'Give a Medium size header');
          break;

          case "small_header":
          updatePopover($container,'Give a small size header');
          break;

          case "text_field":
          updatePopover($container,'Add a small text field');
          break;

          case "agreement":
          updatePopover($container, 'Add a required agreement where users must check to submit the form');
          break;

          case "signature":
          updatePopover($container,'Add a signature field');
          break;

          case "calendar":
          updatePopover($container,'Add a calendar field');
          break;

          case "currency":
          updatePopover($container, 'Add a currency field');
          break;

          case "email_validation":
          updatePopover($container, 'Validate an email');
          break;

          case "check_box":
          updatePopover($container, 'Add a checbox field');
          break;

          case "text_area":
          updatePopover($container,'Add a large text field!');
          break;

          case "file_upload":
          updatePopover($container,'Add a field to upload a picture or PDF');
          break;

          case "description":
            updatePopover($container,'Add a short description field');
            $container.children("div.col-sm-3").addClass("col-md-5");
            $container.children("div.col-md-5").removeClass("col-sm-3");
            break;

          case "contacts":
            updatePopover($container,'Add a contact information or search thru your saved contacts');
            break;

          default:
            updatePopover($container,'Enter Name of Field');
        }

        if (check_option != "description") {
          $container.children("div.col-md-5").addClass("col-sm-3");
          $container.children("div.col-md-5").removeClass("col-md-5");
          
        }
    });
// ctrl f2 bookmark function
  $('.field_type').trigger("change");
}
// // Doc rdy
$(document).ready(window.init)
// // Turbo links rdy (http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links)
$(document).on('page:load', window.init)
</script>

app/views/dynamic_forms_engine/dynamic_form_types/_share_modal.html.erb
<!-- Share Modal -->
<div class="modal fade" id="share-<%= dynamic_form_type.id %>"  tabindex="-1" role="dialog" aria-labelledby="myModalLabel"          aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Share: <%= dynamic_form_type.name %></h4>
      </div>

      <div class="modal-body">
        <p>Copy and paste the following code below onto your website.</p>
        <textarea rows="3"class="form-control"><iframe src="http://localhost:3000/dynamic_forms_engine/dynamic_form_entries/new/<%= dynamic_form_type.id %>?iframe=1" height="800" width="1280"></iframe></textarea>        
      </div>

    </div>
  </div>
</div>

app/views/dynamic_forms_engine/dynamic_form_types/edit.html.erb
<ol class="breadcrumb header">
	<li><%= link_to "Forms", dynamic_form_types_path %></li>
	<li class="active"><%= @dynamic_form_type.name %></li>
</ol>

<%= render 'save_as' %>

app/views/dynamic_forms_engine/dynamic_form_types/index.html.erb
<div class="row">
  <h1 class="col-xs-12 col-sm-6 col-md-6 col-lg-6" id="main-header">My Forms</h1>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <%= link_to '+ Create New Form', new_dynamic_form_type_path, :class => 'btn btn-success pull-right' %>
  </div>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr class='well'>
      <th>Name</th>
      <th>Description</th>
      <th>Form Type</th>
      <th>Public ?</th>
      <th width='1%'></th>
      <th width='1%'></th>
      <th width='1%'></th>
      <th width='1%'></th>
    </tr>
  </thead>

  <tbody>
    <% @dynamic_form_types.each do |dynamic_form_type| %>
      <tr>

        <td><strong><%= dynamic_form_type.name %></strong></td>

        <td><%= dynamic_form_type.description %></td>

        <td><i><%= dynamic_form_type.form_type %></i></td>

        <td><i><%= dynamic_form_type.is_public ? 'Yes' : 'No' %></i></td>

        <td>
          <%= button_tag 'Share', :class => 'btn btn-sm btn-default',
                                  :data => {toggle: 'modal', target: "#share-#{dynamic_form_type.id}"} %>

          <%= render partial: 'share_modal', locals: {dynamic_form_type: dynamic_form_type} %>

        </td>

        <td>
          <%= link_to new_form_entry_path(dynamic_form_type), 
            :class => 'btn btn-sm btn-success' do %>
            <i class="fa fa-pencil-square-o"></i> <%= "View" %>
          <% end %>
        </td>

        <td>
          <a href="<%= form_entries_path(dynamic_form_type) %>">
            <button class="btn btn-sm btn-primary" type="button">
              Entries 
              <span class="badge">
                <%= dynamic_form_type.entries.count  %>
              </span>
            </button>
          </a>
        </td>

        <td><%= link_to 'Edit', edit_dynamic_form_type_path(dynamic_form_type), :class => 'btn btn-sm btn-info' %></td>


      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/dynamic_forms_engine/dynamic_form_types/new.html.erb
<h1>New Form</h1>
<%= render 'form' %>

app/views/dynamic_forms_engine/dynamic_form_types/show.html.erb
<div class="row">
  <h1 class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
  	<%= @dynamic_form_type.name %>
    <%= content_tag :small, @dynamic_form_type.description %>
  </h1>

  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= link_to "New #{@dynamic_form_type.name}", new_dynamic_form_entry_path(:dynamic_form_type_id => params[:id]),:class => "btn btn-success pull-right" %>
    <%= link_to 'Edit Form', edit_dynamic_form_type_path(@dynamic_form_type), :class => 'btn btn-info' %>

  </div>
</div>
  
<table class="table table-striped table-hover">
  <thead>
    <tr class="well">
      <th width="1%">#</th>
      <th width="10%">Name</th>
      <th width="10%">Type</th>
      <th width="10%">Options</th>
      <th width="10%">Required ?</th>
      <th width="10%">Included in Report?</th>
    </tr>
  </thead>
  <tbody>
    <% @form_fields.each do |fields| %>
      <tr>
        <td><%= (fields.field_order)+1 %></td>
      	<td><%= fields.name %></td>
        <td><%= fields.field_type.titleize %></td>
        <td><%= !fields.content_meta.empty? ? fields.content_meta : 'None' %></td>
        <td><%= fields.required ? 'Yes' : 'No' %></td>
        <td><%= fields.included_in_report ? 'Yes' : 'No' %></td>
      </tr>
    <% end %>
  </tbody>
</table>